version: '3.8'

services:
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_AUTH_TOKEN="ls-yuZoyEYu-6745-Fofa-9918-tUPAqURo0e0a"
    ports:
      - "4566:4566"  # LocalStack Gateway
#     - "4572:4572"  # S3
    volumes:
      - "./localstack:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      - ./fake_scans:/mnt/fake_scans

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "9999:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: mcghealth
    ports:
      - "5050:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: mcg
      POSTGRES_PASSWORD: health
      POSTGRES_DB: pcms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  pcms-ui:
    build:
        context: ./pcms-ui
        dockerfile: Dockerfile
    container_name: pcmsui
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
    volumes:
        - ./pcms-ui:/app
        - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]

  app:
    build:  
       context: ./PCMSApi 
       dockerfile: Dockerfile
    container_name: pcmsapi
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=pcms;Username=mcg;Password=health
      - AWS_ServiceURL=http://localstack:4566
    #volumes:
      #- .:/app
    #working_dir: /app
    #command: ["dotnet", "run", "--urls", "http://0.0.0.0:80"]
    depends_on:
      - localstack
      - postgres

volumes:
  postgres_data: